### ISSUE TITLE
Reserved words matcher

### ISSUE THREAD

**Issue by pedro-carranza** [sidilabs/terraform-order#3]
Create a way to store the terraform reserved words and search for them on the code

**Comment by Rodolfodc** [comment]
Define an hierarchy stack of reserved words group. The reserved words are specific for each kind of resources, the matcher should be able to understand it.

**Comment by Rodolfodc** [comment]
Break into two tasks:
1. Reserved words hierarchy engine.
2. Reserved words analyzer (match)

**Comment by pedro-carranza** [comment]
This issue was split into two issues (https://github.com/sidilabs/terraform-order/issues/18 and https://github.com/sidilabs/terraform-order/issues/19)
